const mongoose = require('mongoose');
const { Schema, model } = mongoose;

const bookSchema = new Schema({
    // id is being autogenerated
    name: String,
    genre: String,
    authorId: String
});

module.exports = model('Book', bookSchema);